// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_ScriptImporter","status":true,"description":"スクリプトインポーター 1.0.0\r\nプラグインやスクリプトの前提スクリプトを読み込みます。","parameters":{}},
{"name":"TestScript_1_1","status":true,"description":"","parameters":{}},
{"name":"TestScript_1_2","status":true,"description":"","parameters":{}}
];
